---

server:
  port: 8001

security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mutualFund
    #url: jdbc:mysql://192.168.0.105:3306/mutualFund
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultNamingStrategy
    show-sql: false



